### ISSUE TITLE
feature request: filter events containing a debug key

### ISSUE THREAD

**Issue by ac1989** [klaatu01/woodchuck#16]
I think it would be useful to have a configurable key inside of individual logs that, when present and `true`, prevents woodchuck from shipping that log to the logging platform.

For example a node lambda with the following serverless config;

```yml
woodchuck:
    destination: loggly
    config:
      token: ""
      tag: ""
      exclude_key: "DEBUG"
```

... would not ship a log like this to loggly;

```js
console.log(JSON.stringify({ hello: "world", DEBUG: true }))
```

This would allow the addition and modification of adhoc logs where cloudwatch and cloudwatch insights provide sufficient visibility, and where a user doesn't necessarily want said logs to clutter the end logging platform.

Muchos gracias hermano
